### ISSUE TITLE
Signals: New line Ctrl-c when using export

### ISSUE THREAD

**Issue by QBeukelman** [robertrinh/minishell#52]
Sometimes signal ^C skips a line in the terminal, sometimes not:

<img width="772" alt="^C Skip Line" src="https://github.com/robertrinh/minishell/assets/98453355/f5dab72f-7c6f-4727-b499-e9b46c2e3781">

**Comment by robertrinh** [comment]
This seems like a problem which only happens during `export`. The more exports, the more lines there will be added (A=1  has 1 new line, B=2 has 2 newlines). Below you can see different instances with other commands, which have no issues.

I've been looking all over but I'm not sure what could cause this bug :/ Maybe we need to reset values when there enter a new command?

<img width="554" alt="Screenshot 2024-03-15 at 16 27 45" src="https://github.com/robertrinh/minishell/assets/57951795/ce775b7a-d1e0-4b3f-9df4-404b848b9d4f">

**Comment by robertrinh** [comment]
Some more bugs:
Heredoc is buggy. Not managed to find a fix, but I can determine where the issue is.
Apparantly the child signals  get triggered when in the heredoc process, overwriting the heredoc signals. When the child signals are commented out, the heredoc signals were correctfully called.

Maybe that has to do with fork(), initialising a child process. What confuses me is that after the heredoc fork I specifically call the signal function with enum `HEREDOC`. So I'm not sure why it goes into child signal. 

 Below there has been 4 inputs, after pressing Ctrl-\ there has been 4 child signals of SIGQUIT en pressing Ctrl-c gives 4 new lines too, before killing the process. 

<img width="550" alt="Screenshot 2024-03-15 at 16 36 59" src="https://github.com/robertrinh/minishell/assets/57951795/18d51d87-d782-4a5f-85bb-94e9e26819c1">

**Comment by QBeukelman** [comment]
Hmm tough one. Inception.

**Comment by robertrinh** [comment]
unsetting also causes this issue:

So I think the issue has got to do with env manipulation. It seems minishell thinks that multiple processes are running still, called exit 3 times too before it actually quit the program.

<img width="280" alt="Screenshot 2024-03-22 at 18 19 48" src="https://github.com/robertrinh/minishell/assets/57951795/176f3390-8c30-4437-a291-a718a02fc067">
