### ISSUE TITLE
Single cmd quote `"echo"` → Segfault

### ISSUE THREAD

**Issue by QBeukelman** [robertrinh/minishell#61]
Type a quote as command: e.g. `"echo"`, with no arguments.

Minishell will segfault.

**Comment by robertrinh** [comment]
Issue seems to be that `"echo"` is not recognized as a command, but as a d_quote. Which means that the parser cannot construct the cmd, as there is none. The segfault happens when you try to call count_expand, but there are no args -> segfault.

We should find a way that the first command ignore the quotes in either the lexer or the parser. Let's discuss it :)

```
[minishell]: "echo" hello


========lexer========
d_quote   -      "echo" 
command   -      hello 


========parser========
[20]    166267 segmentation fault (core dumped)  ./minishell -p
```

**Comment by robertrinh** [comment]
`e'c'ho`

apparently, this also needs to be handled; bash does it as well -> quotes between commands

**Comment by QBeukelman** [comment]
`hello"more"more` split after an not before?
